sudo: required
services:
  - docker

before_install:
  - docker build -t dnmahendra/docker-react -f Dockerfile.dev .


script:
  - docker run dnmahendra/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-ap-southeast-2-299028472933"
  bukcet_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
